    # Site settings
title: Dengrc的博客
email: jessedeng.fe@gmail.com
description: Dengrc的博客，专注前端开发

url: "http://dengrc.com"
github_username: Jesse-Deng
permalink: /:year/:month/:day/:title/

markdown: kramdown

keywords: Dengrc 前端开发 JavaScript
